export const test = (name, testFunc) => {
    try {
        testFunc()
        console.log(`âœ…  '${name}' ran successfully`)
    } catch (error) {
        console.error(`ðŸ›‘  '${name}' failed with error`)
        console.error(error)
    }
}

export const assertEquals = (expected, actual) => {
    if (expected !== actual) {
        throw new Error(`Expected '${expected}' but got '${actual}'`)
    }
}
